#
#Sat Jan 31 11:34:28 ECT 2026
goog\:chromeOptions={args\=[start-maximized, incognito, start-maximized, incognito, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
