#
#Tue Mar 31 16:03:10 ECT 2026
goog\:chromeOptions={args\=[start-maximized, incognito, start-maximized, incognito, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
